name: Sync with GitFarm

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global credential.helper store
          echo "https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_PASSWORD }}@git-codecommit.us-east-1.amazonaws.com" > ~/.git-credentials
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Sync repositories
        run: |
          git remote add gitfarm https://git-codecommit.us-east-1.amazonaws.com/v1/repos/Partner-crm-integration-samples
          git fetch gitfarm
          git push origin --all

